arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
name: "HA-NetClient"
description: "NetClient for HA"
version: "0.1.0"
slug: "Netclient For HA"
hassio_api: true
host_network: true
ingress: true
ingress_port: 0
ingress_stream: true
init: false
panel_icon: mdi:vpn
privileged:
- NET_ADMIN
schema:
  tags:
  - match(^tag:[a-zA-Z0-9]-?[a-zA-Z0-9]+$)?
